server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AbhiE?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
service:
  host: http://localhost:8182
  allocation:
    findAll: /allocationG
    findByEmployeeId: /alloEmp/findByEmployeeId