server:
  port: 8182
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AlloService?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
      show-sql: true

